-- Schema for Trivia Game Results

-- 1. Create the table to store trivia game results
CREATE TABLE IF NOT EXISTS public.trivia_game_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    game_id TEXT NOT NULL,
    score INT NOT NULL,
    total_questions INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.trivia_game_results ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies
-- Allow users to read their own trivia results
CREATE POLICY "Allow individual read access on trivia_game_results"
ON public.trivia_game_results
FOR SELECT
USING (auth.uid() = user_id);

-- Allow users to insert their own trivia results
CREATE POLICY "Allow individual insert access on trivia_game_results"
ON public.trivia_game_results
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- 4. Create Indexes for performance
CREATE INDEX IF NOT EXISTS idx_trivia_game_results_user_id ON public.trivia_game_results(user_id);
CREATE INDEX IF NOT EXISTS idx_trivia_game_results_game_id ON public.trivia_game_results(game_id); 