-- Schema and data for Trivia Questions

-- 1. Create the questions table
CREATE TABLE IF NOT EXISTS public.questions (
    id TEXT NOT NULL PRIMARY KEY,
    game_id TEXT NOT NULL,
    question TEXT NOT NULL,
    options TEXT[] NOT NULL,
    correct_answer TEXT NOT NULL,
    explanation TEXT,
    difficulty TEXT,
    category TEXT,
    image_url TEXT,
    image_alt TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable RLS
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies
-- Allow all authenticated users to read questions
CREATE POLICY "Allow authenticated read on questions" ON public.questions
    FOR SELECT TO authenticated USING (true);

-- 4. Create Indexes for performance
CREATE INDEX IF NOT EXISTS idx_questions_game_id ON public.questions(game_id);

-- 5. Insert the questions data
INSERT INTO public.questions (id, game_id, question, options, correct_answer, explanation, difficulty, category, image_url, image_alt) VALUES
('sf-football-1', 'sf-football', 'Which NFL team plays its home games in San Francisco?', '{"49ers", "Raiders", "Giants", "Warriors"}', '49ers', 'The San Francisco 49ers are the NFL team based in San Francisco.', 'easy', 'Sports', '/levis-stadium-49ers.png', 'Levi''s Stadium home of the San Francisco 49ers'),
('sf-football-2', 'sf-football', 'What is the name of the 49ers'' home stadium?', '{"Candlestick Park", "Levi''s Stadium", "Oracle Park", "AT&T Park"}', 'Levi''s Stadium', 'The 49ers moved to Levi''s Stadium in Santa Clara in 2014.', 'easy', 'Sports', '/levis-stadium-49ers.png', 'A wide shot of Levi''s Stadium, home of the 49ers'),
('sf-football-3', 'sf-football', 'How many Super Bowl titles have the 49ers won?', '{"3", "4", "5", "6"}', '5', 'The 49ers won Super Bowls in 1981, 1984, 1988, 1989, and 1994.', 'medium', 'Sports', '/49ers-super-bowl-rings.png', 'A collection of the five San Francisco 49ers Super Bowl rings'),
('sf-football-4', 'sf-football', 'Which legendary coach led the 49ers to multiple Super Bowl victories?', '{"Bill Walsh", "Joe Montana", "Steve Young", "Jerry Rice"}', 'Bill Walsh', 'Bill Walsh coached the 49ers to three Super Bowl victories and revolutionized offensive football.', 'medium', 'Sports', '/bill-walsh-coach.png', 'Portrait of legendary 49ers coach Bill Walsh'),
('sf-football-5', 'sf-football', 'What was the 49ers'' previous home stadium before Levi''s Stadium?', '{"Kezar Stadium", "Candlestick Park", "Oakland Coliseum", "Cow Palace"}', 'Candlestick Park', 'The 49ers played at Candlestick Park from 1971 to 2013.', 'medium', 'Sports', '/candlestick-park-49ers.png', 'An evening shot of the iconic Candlestick Park'),
('sf-football-6', 'sf-football', 'Which 49ers quarterback was known as ''Joe Cool''?', '{"Steve Young", "Joe Montana", "Colin Kaepernick", "Alex Smith"}', 'Joe Montana', 'Joe Montana earned the nickname ''Joe Cool'' for his calm demeanor under pressure.', 'easy', 'Sports', '/joe-montana-cool.png', 'Joe Montana, known as Joe Cool, on the 49ers sideline'),
('sf-football-7', 'sf-football', 'What are the 49ers'' team colors?', '{"Red and Gold", "Red and Silver", "Gold and Black", "Red and White"}', 'Red and Gold', 'The 49ers'' official colors are red and gold, representing the California Gold Rush.', 'easy', 'Sports', '/49ers-red-and-gold-logo.png', 'The San Francisco 49ers red and gold team logo'),
('sf-football-8', 'sf-football', 'Which wide receiver was known as ''The Catch'' for his famous touchdown?', '{"Jerry Rice", "Dwight Clark", "John Taylor", "Terrell Owens"}', 'Dwight Clark', 'Dwight Clark made ''The Catch'' in the 1981 NFC Championship game, sending the 49ers to their first Super Bowl.', 'hard', 'Sports', '/dwight-clark-the-catch.png', 'Dwight Clark making the iconic play known as ''The Catch'''),
('sf-baseball-1', 'sf-baseball', 'Which MLB team plays at Oracle Park?', '{"Giants", "Athletics", "Dodgers", "Padres"}', 'Giants', 'The San Francisco Giants play their home games at Oracle Park.', 'easy', 'Sports', '/oracle-park-giants.png', 'Oracle Park home of the San Francisco Giants'),
('sf-baseball-2', 'sf-baseball', 'What was Oracle Park originally called when it opened?', '{"AT&T Park", "Pacific Bell Park", "SBC Park", "Candlestick Park"}', 'Pacific Bell Park', 'The stadium opened in 2000 as Pacific Bell Park, later renamed AT&T Park, then Oracle Park.', 'medium', 'Sports', '/oracle-park-history.png', 'A historical photo of Oracle Park when it was named Pacific Bell Park'),
('sf-baseball-3', 'sf-baseball', 'How many World Series titles have the Giants won while in San Francisco?', '{"1", "2", "3", "4"}', '3', 'The Giants won World Series titles in 2010, 2012, and 2014 while in San Francisco.', 'medium', 'Sports', '/sf-giants-world-series-trophies.png', 'The three World Series trophies won by the San Francisco Giants'),
('sf-baseball-4', 'sf-baseball', 'What is the famous feature beyond right field at Oracle Park?', '{"McCovey Cove", "Splash Hit Zone", "Giants Bay", "Home Run Harbor"}', 'McCovey Cove', 'McCovey Cove is the body of water beyond right field where home run balls land.', 'easy', 'Sports', '/mccovey-cove-oracle-park.png', 'Kayakers waiting for a splash hit in McCovey Cove at Oracle Park'),
('sf-baseball-5', 'sf-baseball', 'Which Giants player holds the single-season home run record?', '{"Willie Mays", "Barry Bonds", "Willie McCovey", "Buster Posey"}', 'Barry Bonds', 'Barry Bonds hit 73 home runs in 2001, setting the MLB single-season record.', 'medium', 'Sports', '/barry-bonds-73-hr.png', 'Barry Bonds hitting his record-breaking 73rd home run'),
('sf-baseball-6', 'sf-baseball', 'What year did the Giants move from New York to San Francisco?', '{"1957", "1958", "1959", "1960"}', '1958', 'The Giants moved from New York to San Francisco in 1958.', 'hard', 'Sports', '/giants-move-to-sf.png', 'A vintage newspaper announcing the Giants'' move to San Francisco'),
('sf-baseball-7', 'sf-baseball', 'Which Giants player was known as the ''Say Hey Kid''?', '{"Willie Mays", "Willie McCovey", "Orlando Cepeda", "Juan Marichal"}', 'Willie Mays', 'Willie Mays was nicknamed the ''Say Hey Kid'' and is considered one of the greatest players ever.', 'medium', 'Sports', '/willie-mays-say-hey-kid.png', 'A classic photo of the legendary Willie Mays, the ''Say Hey Kid'''),
('sf-baseball-8', 'sf-baseball', 'What is the capacity of Oracle Park?', '{"38,000", "41,915", "45,000", "50,000"}', '41,915', 'Oracle Park has a seating capacity of 41,915 for baseball games.', 'hard', 'Sports', '/oracle-park-full-stadium.png', 'A packed Oracle Park showing its full seating capacity'),
('sf-basketball-1', 'sf-basketball', 'Which NBA team recently moved from Oakland to San Francisco?', '{"Warriors", "Kings", "Lakers", "Clippers"}', 'Warriors', 'The Golden State Warriors moved from Oakland to the Chase Center in San Francisco in 2019.', 'easy', 'Sports', '/chase-center-gsw.png', 'Chase Center home of the Golden State Warriors'),
('sf-basketball-2', 'sf-basketball', 'What is the name of the Warriors'' arena in San Francisco?', '{"Oracle Arena", "Chase Center", "Cow Palace", "War Memorial Gym"}', 'Chase Center', 'The Warriors play at Chase Center in the Mission Bay neighborhood of San Francisco.', 'easy', 'Sports', '/chase-center-gsw.png', 'The exterior of the modern Chase Center in San Francisco'),
('sf-basketball-3', 'sf-basketball', 'How many NBA championships did the Warriors win between 2015-2022?', '{"2", "3", "4", "5"}', '4', 'The Warriors won NBA championships in 2015, 2017, 2018, and 2022.', 'medium', 'Sports', '/gsw-championship-rings.png', 'The four NBA championship rings of the Golden State Warriors dynasty'),
('sf-basketball-4', 'sf-basketball', 'Which Warriors player holds the NBA record for most 3-pointers in a season?', '{"Stephen Curry", "Klay Thompson", "Kevin Durant", "Draymond Green"}', 'Stephen Curry', 'Stephen Curry set the record with 402 three-pointers made in the 2015-16 season.', 'medium', 'Sports', '/steph-curry-3-pointer.png', 'Stephen Curry shooting his signature three-point shot'),
('sf-basketball-5', 'sf-basketball', 'What nickname is given to the Warriors'' backcourt duo?', '{"Splash Brothers", "Warrior Twins", "Bay Bombers", "Golden Guards"}', 'Splash Brothers', 'Stephen Curry and Klay Thompson are known as the ''Splash Brothers'' for their three-point shooting.', 'easy', 'Sports', '/splash-brothers-curry-thompson.png', 'Stephen Curry and Klay Thompson, the ''Splash Brothers'', celebrating'),
('sf-basketball-6', 'sf-basketball', 'Before moving to San Francisco, what city were the Warriors based in?', '{"Philadelphia", "San Diego", "Oakland", "San Jose"}', 'Oakland', 'The Warriors were based in Oakland from 1971 to 2019.', 'medium', 'Sports', '/oracle-arena-oakland-gsw.png', 'The exterior of Oracle Arena in Oakland, former home of the Warriors'),
('sf-basketball-7', 'sf-basketball', 'Who is the head coach that led the Warriors to their recent championships?', '{"Mark Jackson", "Don Nelson", "Steve Kerr", "Alvin Gentry"}', 'Steve Kerr', 'Steve Kerr became head coach in 2014 and has led the team to four NBA titles.', 'medium', 'Sports', '/steve-kerr-coach-gsw.png', 'Head coach Steve Kerr directing the Golden State Warriors'),
('sf-basketball-8', 'sf-basketball', 'What iconic feature is the city of San Francisco known for?', '{"Golden Gate Bridge", "Statue of Liberty", "Eiffel Tower", "Space Needle"}', 'Golden Gate Bridge', 'The Golden Gate Bridge is San Francisco''s most famous landmark.', 'easy', 'General', '/golden-gate-bridge-sf.png', 'The iconic Golden Gate Bridge at sunset'),
('sf-districts-1', 'sf-districts', 'Which district is known for its vibrant murals and Latino culture?', '{"The Mission", "The Castro", "Haight-Ashbury", "North Beach"}', 'The Mission', 'The Mission District is famous for its colorful street art and deep Latino roots.', 'easy', 'Geography', '/mission-district-sf-murals.png', 'Vibrant murals on a building in the Mission District'),
('sf-districts-2', 'sf-districts', 'What district is considered the center of LGBTQ+ culture in San Francisco?', '{"The Castro", "SoMa", "Nob Hill", "Russian Hill"}', 'The Castro', 'The Castro is a world-renowned symbol of LGBTQ+ activism and community.', 'easy', 'Culture', '/castro-theatre-sf.png', 'The iconic Castro Theatre with its rainbow crosswalk'),
('sf-districts-3', 'sf-districts', 'Which district is famous for being the birthplace of the 1960s counterculture movement?', '{"Haight-Ashbury", "Financial District", "Chinatown", "Fisherman''s Wharf"}', 'Haight-Ashbury', 'Haight-Ashbury was the epicenter of the ''Summer of Love'' and the hippie movement.', 'medium', 'History', '/haight-ashbury-sf-sign.png', 'The famous Haight-Ashbury street sign'),
('sf-districts-4', 'sf-districts', 'In which district would you find the famous ''Painted Ladies'' Victorian houses?', '{"Hayes Valley", "Alamo Square", "Pacific Heights", "The Fillmore"}', 'Alamo Square', 'The ''Painted Ladies'' are located on Steiner Street, bordering Alamo Square Park.', 'medium', 'Landmarks', '/painted-ladies-sf.png', 'The famous ''Painted Ladies'' Victorian houses across from Alamo Square'),
('sf-districts-5', 'sf-districts', 'Which district is known as San Francisco''s ''Little Italy''?', '{"North Beach", "Chinatown", "Japantown", "Russian Hill"}', 'North Beach', 'North Beach is famous for its Italian heritage, cafes, and restaurants.', 'medium', 'Culture', '/north-beach-sf.png', 'A street scene in North Beach, San Francisco''s ''Little Italy'''),
('sf-districts-6', 'sf-districts', 'The oldest Chinatown in North America is located in which SF district?', '{"Chinatown", "SoMa", "Financial District", "Tenderloin"}', 'Chinatown', 'San Francisco''s Chinatown is the largest Chinese enclave outside of Asia and the oldest in North America.', 'easy', 'History', '/chinatown-gate-sf.png', 'The iconic Dragon''s Gate entrance to San Francisco''s Chinatown'),
('sf-districts-7', 'sf-districts', 'Which district is home to Coit Tower?', '{"Telegraph Hill", "Nob Hill", "Russian Hill", "Twin Peaks"}', 'Telegraph Hill', 'Coit Tower is located in the Telegraph Hill neighborhood, offering panoramic city views.', 'medium', 'Landmarks', '/coit-tower-sf.png', 'Coit Tower standing atop Telegraph Hill'),
('sf-districts-8', 'sf-districts', 'Which district is known for its stunning views of the Golden Gate Bridge?', '{"The Presidio", "Golden Gate Park", "The Marina", "Fisherman''s Wharf"}', 'The Presidio', 'The Presidio, a former military post, offers some of the most spectacular views of the Golden Gate Bridge.', 'medium', 'Geography', '/presidio-gg-bridge-view.png', 'A stunning view of the Golden Gate Bridge from the Presidio'),
('sf-tourist-spots-1', 'sf-tourist-spots', 'What is the name of the infamous former federal prison located on an island in the San Francisco Bay?', '{"Alcatraz Island", "Angel Island", "Treasure Island", "Yerba Buena Island"}', 'Alcatraz Island', 'Alcatraz was a notorious federal prison from 1934 to 1963 and is now a popular tourist attraction.', 'easy', 'History', '/alcatraz-island-sf.png', 'The infamous Alcatraz Island prison in the San Francisco Bay'),
('sf-tourist-spots-2', 'sf-tourist-spots', 'What is the most visited tourist attraction in San Francisco?', '{"Fisherman''s Wharf", "Golden Gate Bridge", "Alcatraz Island", "Union Square"}', 'Fisherman''s Wharf', 'Fisherman''s Wharf, particularly Pier 39, is the most visited tourist destination in San Francisco.', 'easy', 'Attractions', '/fishermans-wharf-sf.png', 'The bustling Fisherman''s Wharf with sea lions in the background'),
('sf-tourist-spots-3', 'sf-tourist-spots', 'What are the famous vehicles that travel up and down San Francisco''s steep hills?', '{"Cable Cars", "Trolleybuses", "Streetcars", "Funiculars"}', 'Cable Cars', 'San Francisco''s manually operated cable cars are a historic and iconic mode of transportation.', 'easy', 'Transportation', '/sf-cable-car.png', 'An iconic San Francisco cable car climbing a steep hill'),
('sf-tourist-spots-4', 'sf-tourist-spots', 'Which large urban park is bigger than New York''s Central Park?', '{"Golden Gate Park", "Presidio", "Lake Merced Park", "Dolores Park"}', 'Golden Gate Park', 'At 1,017 acres, Golden Gate Park is about 20% larger than Central Park.', 'medium', 'Parks', '/golden-gate-park-sf.png', 'An aerial view of the vast and green Golden Gate Park'),
('sf-tourist-spots-5', 'sf-tourist-spots', 'What is the famously crooked street in San Francisco?', '{"Lombard Street", "Filbert Street", "Hyde Street", "Powell Street"}', 'Lombard Street', 'Lombard Street is famous for its eight sharp turns on a steep, one-block section.', 'easy', 'Landmarks', '/lombard-street-sf.png', 'Cars carefully navigating down the crooked Lombard Street'),
('sf-tourist-spots-6', 'sf-tourist-spots', 'Which museum is known for its ''living roof'' of native California plants?', '{"California Academy of Sciences", "de Young Museum", "SFMOMA", "Exploratorium"}', 'California Academy of Sciences', 'The California Academy of Sciences in Golden Gate Park features a 2.5-acre living roof.', 'hard', 'Museums', '/california-academy-of-sciences-roof.png', 'The unique living roof of the California Academy of Sciences'),
('sf-tourist-spots-7', 'sf-tourist-spots', 'At which pier can you see a colony of sea lions?', '{"Pier 39", "Pier 45", "Pier 7", "Ferry Building"}', 'Pier 39', 'A colony of California sea lions has famously made the docks of Pier 39 their home.', 'easy', 'Wildlife', '/pier-39-sea-lions-sf.png', 'A large colony of sea lions basking on the docks of Pier 39'),
('sf-tourist-spots-8', 'sf-tourist-spots', 'Which tower offers panoramic views from Telegraph Hill?', '{"Coit Tower", "Transamerica Pyramid", "Sutro Tower", "Salesforce Tower"}', 'Coit Tower', 'Coit Tower, built in 1933, provides 360-degree views of the city and bay.', 'medium', 'Landmarks', '/coit-tower-view-sf.png', 'The view of San Francisco from the top of Coit Tower'),
('sf-day-trips-1', 'sf-day-trips', 'Which famous wine region is a popular day trip north of San Francisco?', '{"Napa Valley", "Sonoma Valley", "Livermore Valley", "Carmel Valley"}', 'Napa Valley', 'Napa Valley is world-renowned for its vineyards and wineries, located about an hour''s drive north.', 'easy', 'Wine Country', '/napa-valley-vineyards.png', 'Lush vineyards in the beautiful Napa Valley'),
('sf-day-trips-2', 'sf-day-trips', 'What national monument, located just north of the Golden Gate Bridge, is famous for its giant redwood trees?', '{"Muir Woods", "Yosemite", "Redwood National Park", "Pinnacles National Park"}', 'Muir Woods', 'Muir Woods National Monument is home to towering old-growth coast redwood trees.', 'easy', 'Nature', '/muir-woods-redwoods.png', 'Towering giant redwood trees in Muir Woods'),
('sf-day-trips-3', 'sf-day-trips', 'Which coastal town south of SF is known for its charming European-style architecture?', '{"Carmel-by-the-Sea", "Santa Cruz", "Half Moon Bay", "Monterey"}', 'Carmel-by-the-Sea', 'Carmel-by-the-Sea is a picturesque town known for its storybook cottages and art galleries.', 'medium', 'Coastal Towns', '/carmel-by-the-sea.png', 'A charming, storybook-style cottage in Carmel-by-the-Sea'),
('sf-day-trips-4', 'sf-day-trips', 'Which city, home to a famous university, is located across the bay from San Francisco?', '{"Berkeley", "Oakland", "Palo Alto", "Sausalito"}', 'Berkeley', 'Berkeley is home to the University of California, Berkeley, and is located in the East Bay.', 'medium', 'Cities', '/berkeley-university-campus.png', 'The iconic Sather Tower on the UC Berkeley campus'),
('sf-day-trips-5', 'sf-day-trips', 'What scenic driving route runs along the coast south of San Francisco?', '{"Highway 1", "Route 66", "Pacific Coast Highway", "Interstate 5"}', 'Highway 1', 'California State Route 1, also known as the Pacific Coast Highway, offers breathtaking coastal views.', 'easy', 'Scenic Drives', '/highway-1-bixby-bridge.png', 'A car driving along Highway 1 with the Bixby Bridge in the background'),
('sf-day-trips-6', 'sf-day-trips', 'Which seaside city is famous for its boardwalk amusement park and surfing culture?', '{"Santa Cruz", "Half Moon Bay", "Capitola", "Pacifica"}', 'Santa Cruz', 'Santa Cruz is well-known for its historic boardwalk, surfing spots, and laid-back vibe.', 'medium', 'Coastal Towns', '/santa-cruz-boardwalk.png', 'The roller coaster at the Santa Cruz Beach Boardwalk'),
('sf-day-trips-7', 'sf-day-trips', 'What is the main attraction in the city of Monterey?', '{"Monterey Bay Aquarium", "Cannery Row", "Fisherman''s Wharf", "17-Mile Drive"}', 'Monterey Bay Aquarium', 'The Monterey Bay Aquarium is a world-class aquarium renowned for its marine life exhibits.', 'medium', 'Attractions', '/monterey-bay-aquarium.png', 'The stunning Open Sea exhibit at the Monterey Bay Aquarium'),
('sf-day-trips-8', 'sf-day-trips', 'Which waterfront town is known for its houseboats and views of San Francisco?', '{"Sausalito", "Tiburon", "Muir Beach", "Stinson Beach"}', 'Sausalito', 'Sausalito, just across the Golden Gate Bridge, is famous for its artistic houseboat communities and stunning city views.', 'medium', 'Cities', '/sausalito-houseboats.png', 'Colorful houseboats docked in Sausalito, with the San Francisco skyline in the distance')
ON CONFLICT (id) DO NOTHING; 